INPUT_IMAGES_PATH="input images"
OUTPUT_IMAGES_PATH="output images" 
VARI_IMAGES_GRAY="output images/VARI grayscale" 
VARI_IMAGES_COLOR="output images/VARI colormap" 
GLI_IMAGES_GRAY="output images/GLI grayscale"
GLI_IMAGES_COLOR="output images/GLI colormap"   
VI_IMAGES_GRAY="output images/VI grayscale" 
VI_IMAGES_COLOR="output images/VI colormap"
IMG_EXTENSIONS=[".png",".jpg",".jpeg"]  